name: dart_jsonwebtoken
description: A dart implementation of the famous javascript library 'jsonwebtoken' (JWT).
version: 2.4.2
repository: https://github.com/jonasroussel/dart_jsonwebtoken
homepage: https://github.com/jonasroussel/dart_jsonwebtoken#readme

environment:
  sdk: '>=2.12.0 <3.0.0'

false_secrets:
 - /example/ec_private.pem
 - /example/ec_public.pem
 - /example/rsa_private.pem
 - /example/rsa_public.pem

dependencies:
  crypto: ^3.0.1
  pointycastle: ^3.5.0
  convert: ^3.0.1
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
