name: dart_jsonwebtoken
description: A dart implementation of the famous javascript library 'jsonwebtoken' (JWT).
version: 2.8.1
repository: https://github.com/jonasroussel/dart_jsonwebtoken
homepage: https://github.com/jonasroussel/dart_jsonwebtoken#readme

environment:
  sdk: ">=2.12.0 <4.0.0"

false_secrets:
  - /example/ec_private.pem
  - /example/ec_public.pem
  - /example/rsa_private.pem
  - /example/rsa_public.pem

dependencies:
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  convert: ^3.1.1
  collection: ^1.17.2
  ed25519_edwards: ^0.3.1

dev_dependencies:
  lints: ^2.0.1
