name: dart_jsonwebtoken
description: An easy to use JSON Web Token (JWT) implementation in Dart with all algorithms supported.
version: 3.1.1
repository: https://github.com/jonasroussel/dart_jsonwebtoken
homepage: https://github.com/jonasroussel/dart_jsonwebtoken#readme

environment:
  sdk: ">=2.12.0 <4.0.0"

false_secrets:
  - /example/*.pem
  - /test/*
  - /README.md

dependencies:
  crypto: ^3.0.6
  pointycastle: ^3.7.3
  convert: ^3.1.2
  collection: ^1.17.1
  ed25519_edwards: ^0.3.1
  clock: ^1.1.2

dev_dependencies:
  fake_async: ^1.3.3
  lints: ^5.1.1
  test: ^1.25.15
