name: dart_jsonwebtoken
description: A dart implementation of the famous javascript library 'jsonwebtoken' (JWT).
version: 2.3.2
repository: https://github.com/jonasroussel/dart_jsonwebtoken
homepage: https://github.com/jonasroussel/dart_jsonwebtoken#readme

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1
  pointycastle: ">=3.0.1 <=3.1.2" # ^3.1.3 is incompatible with flutter web
  convert: ^3.0.1
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
