name: dart_jsonwebtoken
description: A dart implementation of the famous javascript library 'jsonwebtoken' (JWT).
version: 2.11.0
repository: https://github.com/jonasroussel/dart_jsonwebtoken
homepage: https://github.com/jonasroussel/dart_jsonwebtoken#readme

environment:
  sdk: ">=2.12.0 <4.0.0"

false_secrets:
  - /example/*.pem
  - /test/*

dependencies:
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  convert: ^3.1.1
  collection: ^1.17.1
  ed25519_edwards: ^0.3.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
